from typing import List, Optional, Protocol, runtime_checkable

from py_sematic_taxonomy.domain.entities import Concept, ConceptScheme, Edge


@runtime_checkable
class SKOSRepository(Protocol):
    async def list_schemes(self) -> List[Concept]: ...

    async def list_concepts(self) -> List[ConceptScheme]: ...

    async def get_by_iri(self, object_iri: str) -> Optional[Concept | ConceptScheme]: ...

    async def create_concept(self, concept: Concept) -> Concept: ...

    async def create_scheme(self, scheme: ConceptScheme) -> ConceptScheme: ...

    async def update_concept(self, concept: Concept) -> Concept: ...

    async def update_scheme(self, scheme: ConceptScheme) -> ConceptScheme: ...

    async def delete_concept(self, concept: Concept) -> bool: ...

    async def delete_scheme(self, scheme: ConceptScheme) -> bool: ...
